// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/geometry.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RectRequest struct {
	Height               float32  `protobuf:"fixed32,1,opt,name=height,proto3" json:"height,omitempty"`
	Width                float32  `protobuf:"fixed32,2,opt,name=width,proto3" json:"width,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RectRequest) Reset()         { *m = RectRequest{} }
func (m *RectRequest) String() string { return proto.CompactTextString(m) }
func (*RectRequest) ProtoMessage()    {}
func (*RectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f550afaa94df5aef, []int{0}
}

func (m *RectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RectRequest.Unmarshal(m, b)
}
func (m *RectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RectRequest.Marshal(b, m, deterministic)
}
func (m *RectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RectRequest.Merge(m, src)
}
func (m *RectRequest) XXX_Size() int {
	return xxx_messageInfo_RectRequest.Size(m)
}
func (m *RectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RectRequest proto.InternalMessageInfo

func (m *RectRequest) GetHeight() float32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *RectRequest) GetWidth() float32 {
	if m != nil {
		return m.Width
	}
	return 0
}

type AreaResponse struct {
	Result               float32  `protobuf:"fixed32,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AreaResponse) Reset()         { *m = AreaResponse{} }
func (m *AreaResponse) String() string { return proto.CompactTextString(m) }
func (*AreaResponse) ProtoMessage()    {}
func (*AreaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f550afaa94df5aef, []int{1}
}

func (m *AreaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaResponse.Unmarshal(m, b)
}
func (m *AreaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaResponse.Marshal(b, m, deterministic)
}
func (m *AreaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaResponse.Merge(m, src)
}
func (m *AreaResponse) XXX_Size() int {
	return xxx_messageInfo_AreaResponse.Size(m)
}
func (m *AreaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AreaResponse proto.InternalMessageInfo

func (m *AreaResponse) GetResult() float32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type PerimeterResponse struct {
	Result               float32  `protobuf:"fixed32,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PerimeterResponse) Reset()         { *m = PerimeterResponse{} }
func (m *PerimeterResponse) String() string { return proto.CompactTextString(m) }
func (*PerimeterResponse) ProtoMessage()    {}
func (*PerimeterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f550afaa94df5aef, []int{2}
}

func (m *PerimeterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PerimeterResponse.Unmarshal(m, b)
}
func (m *PerimeterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PerimeterResponse.Marshal(b, m, deterministic)
}
func (m *PerimeterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PerimeterResponse.Merge(m, src)
}
func (m *PerimeterResponse) XXX_Size() int {
	return xxx_messageInfo_PerimeterResponse.Size(m)
}
func (m *PerimeterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PerimeterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PerimeterResponse proto.InternalMessageInfo

func (m *PerimeterResponse) GetResult() float32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*RectRequest)(nil), "geometry.RectRequest")
	proto.RegisterType((*AreaResponse)(nil), "geometry.AreaResponse")
	proto.RegisterType((*PerimeterResponse)(nil), "geometry.PerimeterResponse")
}

func init() {
	proto.RegisterFile("proto/geometry.proto", fileDescriptor_f550afaa94df5aef)
}

var fileDescriptor_f550afaa94df5aef = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4f, 0xcd, 0xcf, 0x4d, 0x2d, 0x29, 0xaa, 0xd4, 0x03, 0x73, 0x85, 0x38, 0x60,
	0x7c, 0x25, 0x6b, 0x2e, 0xee, 0xa0, 0xd4, 0xe4, 0x92, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12,
	0x21, 0x31, 0x2e, 0xb6, 0x8c, 0xd4, 0xcc, 0xf4, 0x8c, 0x12, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xa6,
	0x20, 0x28, 0x4f, 0x48, 0x84, 0x8b, 0xb5, 0x3c, 0x33, 0xa5, 0x24, 0x43, 0x82, 0x09, 0x2c, 0x0c,
	0xe1, 0x28, 0xa9, 0x71, 0xf1, 0x38, 0x16, 0xa5, 0x26, 0x06, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15,
	0xa7, 0x82, 0x74, 0x17, 0xa5, 0x16, 0x97, 0xe6, 0xc0, 0x75, 0x43, 0x78, 0x4a, 0xda, 0x5c, 0x82,
	0x01, 0xa9, 0x45, 0x99, 0xb9, 0xa9, 0x25, 0xa9, 0x45, 0x84, 0x14, 0x1b, 0x75, 0x32, 0x72, 0xf1,
	0xbb, 0x43, 0x9d, 0x17, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c, 0x2a, 0x64, 0xca, 0xc5, 0x02, 0xb2,
	0x48, 0x48, 0x54, 0x0f, 0xee, 0x11, 0x24, 0x57, 0x4b, 0x89, 0x21, 0x84, 0x51, 0xdc, 0x63, 0xcf,
	0xc5, 0x09, 0xb7, 0x17, 0x97, 0x5e, 0x69, 0x84, 0x30, 0x86, 0x1b, 0x9d, 0x8c, 0xa3, 0x0c, 0xd3,
	0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x53, 0x4a, 0x8b, 0xb3, 0x75, 0x93,
	0x33, 0x12, 0xf3, 0x92, 0x53, 0x73, 0x72, 0xf2, 0x8b, 0xf4, 0xd3, 0xf3, 0x75, 0xd3, 0x8b, 0x0a,
	0x92, 0x75, 0x53, 0x2b, 0x12, 0x73, 0x0b, 0x72, 0x52, 0x8b, 0xf5, 0xc1, 0x81, 0x9b, 0xc4, 0x06,
	0xa6, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x34, 0xf3, 0x18, 0x76, 0x7b, 0x01, 0x00, 0x00,
}
